import { QueryProvider } from '@/providers/QueryProvider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
};

// components
import Footer from '@/components/footer/Footer';
import Header from '@/components/header/Header';
import SideBar from '@/components/sidebar/SideBar';

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <QueryProvider>
                    <Header />
                    <main className='max-w-7xl mx-auto px-4'>
                        <h2 className='hidden'>'메인 페이지 영역'</h2>
                        {children}
                    </main>
                    <Footer />
                    <SideBar />
                </QueryProvider>
            </body>
        </html>
    );
}
